name: koppen-knets
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - h5py
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - psutil
  - jax
  - pytest
  - pip
  - pip:
      - torch